services:
  postgres:
    container_name: postgres-sql-simulation
    image: postgres
    environment:
      POSTGRES_USER: innosoc
      POSTGRES_PASSWORD: Docker@2024d
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: simulation
    volumes:
      - postgres:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - spring-nw-sim
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-simulation
    image: maildev/maildev
    ports:
      - "1083:1080"
      - "1029:1025"

networks:
  spring-nw-sim:
    driver: bridge

volumes:
  postgres:
    driver: local
