services:
  postgres:
    container_name: postgres-sql-simulation
    image: postgres
    environment:
      POSTGRES_USER: innosoc
      POSTGRES_PASSWORD: Docker@2024d
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: simulation
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-simulation
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
