spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
      cache: false
      encoding: UTF-8
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api-sim/v1/


